name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  static_test:
    name: static_test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: python_setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: python_packages
        run: python -m pip install --upgrade pip
          pip install pandas sklearn black flake8
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
          
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: ghcr login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: 
