name: CI

on:
  push:
    branches:
      - main

jobs:
  static_test:
    name: static_test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: python_packages
        run: python -m pip install --upgrade pip
          pip install pandas sklearn black flake8
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
          
  build:
    name: build container
    runs-on: ubuntu-latest
    needs: static_test
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: build export
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: test_tag
      - name: test
        run: |
          docker run -d --name dckr test_tag
          docker cp dckr:/details.txt /details.txt
          docker kill dckr
          docker rm dckr
      - name: build push
        uses: docker/build-push-action@v3
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test
