name: CD

on:
  push:
    branches:
      - dev
      
jobs:
  build_and_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: docker_image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cp ./test/Dockerfile ./
            cp ./test/app.py ./
            cp -r ./test/templates ./
            cp ./preprocessing_train.py ./
            docker stop flask_docker
            docker rm flask_docker
            docker system prune -a
            chmod 777 Dockerfile
            docker build -t flask_app .
            docker run -d -p 0.0.0.0:5000:5000/tcp --name flask_docker flask_app:latest
            
  
