name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  static_test:
    name: static_test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: python_packages
        run: pip install black flake8
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
      - name: docker build test
        
          
  
  upload:
    name: upload
    runs-on: ubuntu-latest
    needs: static_test
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: upload_Dockerfile
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './Dockerfile'
          destination: 'bucket_cjh980803'
      - name: upload_preprocessing_train
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './preprocessing_train.py'
          destination: 'bucket_cjh980803'
      - name: upload_flask_app
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './app.py'
          destination: 'bucket_cjh980803'
      - name: upload_templates
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './templates'
      - name: set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: copy files to compute engine
        run: |-
          gsutil cp gs://bucket_cjh980803/Dockerfile .
          gsutil cp gs://bucket_cjh980803/preprocessing_train.py .
          gsutil cp gs://bucket_cjh980803/app.py .
          gsutil cp gs://bucket_cjh980803/templates/index.html .
          gsutil cp gs://bucket_cjh980803/templates/result.html .
          gcloud compute scp ./Dockerfile cjh980803@instance:~/ --zone=asia-northeast3-a
          gcloud compute scp ./preprocessing_train.py cjh980803@instance:~/ --zone=asia-northeast3-a
          gcloud compute scp ./app.py cjh980803@instance:~/ --zone=asia-northeast3-a
          gcloud compute scp ./index.html cjh980803@instance:~/templates/ --zone=asia-northeast3-a
          gcloud compute scp ./result.html cjh980803@instance:~/templates/ --zone=asia-northeast3-a
