name: "Data collection and train"

on:
  push:
    branches:
      - main
    
jobs:
  data_collection:
    name: data_collection
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: python_packages
        run: python -m pip install --upgrade pip
          pip install pandas sklearn transformers datasets Beautifulsoup4
      - name: collection
        run: python3 collection.py
        
  train:
    name: train
    runs-on: self-hosted
    needs: data_collection
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: python_packages
        run: py -m pip install pandas sklearn black flake8 transformers datasets torch
      - name: train
        run: python preprocessing_train.py
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - id: 'upload_file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './model'
          destination: 'bucket_cjh980803'
        

