name: "Data collection and train"

on:
  push:
    branches:
      - main
    
jobs:
  data_collection:
    name: data_collection
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: python_packages
        run: python -m pip install --upgrade pip
          pip install pandas sklearn transformers datasets Beautifulsoup
      - name: collection
        run: python3 collection.py
        
  train:
    name: train
    runs-on: self-hosted
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: 'service-180115510323@gs-project-accounts.iam.gserviceaccount.com'
      - id: 'upload_file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './train_data.csv'
          destination: 'bucket_cjh980803/train_data.csv'
        

