name: main

on:
  push:
    branches:
      - main
      
jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: upload_Dockerfile
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './Dockerfile'
          destination: 'bucket_cjh980803'
      - name: upload_preprocessing_train
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './preprocessing_train.py'
          destination: 'bucket_cjh980803'
      - name: upload_flask_app
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './app.py'
          destination: 'bucket_cjh980803'
      - name: upload_templates
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './templates'
          destination: 'bucket_cjh980803'
      - name: set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: copy files to compute engine
        run: |-
          gsutil cp gs://bucket_cjh980803/Dockerfile .
          gsutil cp gs://bucket_cjh980803/preprocessing_train.py .
          gsutil cp gs://bucket_cjh980803/app.py .
          gsutil cp gs://bucket_cjh980803/templates/index.html .
          gsutil cp gs://bucket_cjh980803/templates/result.html .
          gcloud compute scp ./Dockerfile cjh980803@instance:~/ --zone=asia-northeast3-a
          gcloud compute scp ./preprocessing_train.py cjh980803@instance:~/ --zone=asia-northeast3-a
          gcloud compute scp ./app.py cjh980803@instance:~/ --zone=asia-northeast3-a
          gcloud compute scp ./index.html cjh980803@instance:~/templates --zone=asia-northeast3-a
          gcloud compute scp ./result.html cjh980803@instance:~/templates/ --zone=asia-northeast3-a
          
  
  build_and_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: docker_image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop flask_docker
            docker rm flask_docker
            docker system prune -a -f
            chmod 777 Dockerfile
            docker build -t flask_app .
            docker run -d -p 0.0.0.0:5000:5000/tcp --name flask_docker flask_app:latest
            
  
