name: Your CICD Pipeline Name
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo test
    - name: python setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
      
    - name: py1
      run: python3 1.py
    - name: py2
      run: python3 2.py
