name: Your CICD Pipeline Name
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo test
    - name: py1
      run: 1.py
    - name: py2
      run: 2.py
