name: test

on:
  push:
    branches:
      - dev
      
jobs:
  build_and_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: python package
        run: pip install requests pytest
      - name: test
        run: pytest dynamic_test.py
