name: "Data collection and train"
on:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  data_collection:
    name: data_collection
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3
      - name: python_packages
        run: python -m pip install --upgrade pip
          pip install pandas sklearn transformers datasets
      - name: collection
        run: python3 collection.py
